<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AttendanceVerificationConditionsTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('attendance_verification_conditions')->truncate();
        
        \DB::table('attendance_verification_conditions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'core_firms_id' => NULL,
                'workplan_category' => 1,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '12',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            1 => 
            array (
                'id' => 2,
                'core_firms_id' => NULL,
                'workplan_category' => 1,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            2 => 
            array (
                'id' => 3,
                'core_firms_id' => NULL,
                'workplan_category' => 1,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_shifts',
                'value' => '11',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            3 => 
            array (
                'id' => 4,
                'core_firms_id' => NULL,
                'workplan_category' => 1,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'piece',
                'period' => 'week',
                'value' => '2',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            4 => 
            array (
                'id' => 5,
                'core_firms_id' => NULL,
                'workplan_category' => 3,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '12',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            5 => 
            array (
                'id' => 6,
                'core_firms_id' => NULL,
                'workplan_category' => 3,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            6 => 
            array (
                'id' => 7,
                'core_firms_id' => NULL,
                'workplan_category' => 3,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_shifts',
                'value' => '8',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            7 => 
            array (
                'id' => 8,
                'core_firms_id' => NULL,
                'workplan_category' => 3,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'piece',
                'period' => 'week',
                'value' => '2',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            8 => 
            array (
                'id' => 9,
                'core_firms_id' => NULL,
                'workplan_category' => 4,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '24',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            9 => 
            array (
                'id' => 10,
                'core_firms_id' => NULL,
                'workplan_category' => 4,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '72',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            10 => 
            array (
                'id' => 11,
                'core_firms_id' => NULL,
                'workplan_category' => 4,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_shifts',
                'value' => '8',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            11 => 
            array (
                'id' => 12,
                'core_firms_id' => NULL,
                'workplan_category' => 4,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'piece',
                'period' => 'week',
                'value' => '2',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            12 => 
            array (
                'id' => 13,
                'core_firms_id' => NULL,
                'workplan_category' => 5,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '12',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:41',
            ),
            13 => 
            array (
                'id' => 14,
                'core_firms_id' => NULL,
                'workplan_category' => 5,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            14 => 
            array (
                'id' => 15,
                'core_firms_id' => NULL,
                'workplan_category' => 5,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_shifts',
                'value' => '8',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            15 => 
            array (
                'id' => 16,
                'core_firms_id' => NULL,
                'workplan_category' => 5,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'piece',
                'period' => 'week',
                'value' => '2',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            16 => 
            array (
                'id' => 17,
                'core_firms_id' => NULL,
                'workplan_category' => 5,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'uninterrupted_hours',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            17 => 
            array (
                'id' => 18,
                'core_firms_id' => NULL,
                'workplan_category' => 5,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_split_shifts',
                'value' => '2',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            18 => 
            array (
                'id' => 19,
                'core_firms_id' => NULL,
                'workplan_category' => 6,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '12',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            19 => 
            array (
                'id' => 20,
                'core_firms_id' => NULL,
                'workplan_category' => 6,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '72',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            20 => 
            array (
                'id' => 21,
                'core_firms_id' => NULL,
                'workplan_category' => 6,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_shifts',
                'value' => '8',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            21 => 
            array (
                'id' => 22,
                'core_firms_id' => NULL,
                'workplan_category' => 6,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_rest_days',
                'value' => '22',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            22 => 
            array (
                'id' => 23,
                'core_firms_id' => NULL,
                'workplan_category' => 6,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'piece',
                'period' => 'week',
                'value' => '1',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            23 => 
            array (
                'id' => 24,
                'core_firms_id' => NULL,
                'workplan_category' => 6,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'uninterrupted_hours',
                'period' => 'week',
                'value' => '24',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            24 => 
            array (
                'id' => 25,
                'core_firms_id' => NULL,
                'workplan_category' => 6,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'full_day',
                'period' => 'week',
                'value' => '1',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            25 => 
            array (
                'id' => 26,
                'core_firms_id' => NULL,
                'workplan_category' => 6,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_split_shifts',
                'value' => '4',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            26 => 
            array (
                'id' => 27,
                'core_firms_id' => NULL,
                'workplan_category' => 7,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '12',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            27 => 
            array (
                'id' => 28,
                'core_firms_id' => NULL,
                'workplan_category' => 7,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            28 => 
            array (
                'id' => 29,
                'core_firms_id' => NULL,
                'workplan_category' => 7,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_shifts',
                'value' => '8',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            29 => 
            array (
                'id' => 30,
                'core_firms_id' => NULL,
                'workplan_category' => 7,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'piece',
                'period' => 'week',
                'value' => '2',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            30 => 
            array (
                'id' => 31,
                'core_firms_id' => NULL,
                'workplan_category' => 7,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'uninterrupted_hours',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            31 => 
            array (
                'id' => 32,
                'core_firms_id' => NULL,
                'workplan_category' => 8,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '12',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            32 => 
            array (
                'id' => 33,
                'core_firms_id' => NULL,
                'workplan_category' => 8,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            33 => 
            array (
                'id' => 34,
                'core_firms_id' => NULL,
                'workplan_category' => 8,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_shifts',
                'value' => '8',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            34 => 
            array (
                'id' => 35,
                'core_firms_id' => NULL,
                'workplan_category' => 8,
                'type' => 'workday',
                'operator' => 'maximum',
                'unit' => 'piece',
                'period' => 'between_rest_days',
                'value' => '6',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            35 => 
            array (
                'id' => 36,
                'core_firms_id' => NULL,
                'workplan_category' => 8,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'sunday',
                'period' => 'month',
                'value' => '1',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            36 => 
            array (
                'id' => 37,
                'core_firms_id' => NULL,
                'workplan_category' => 9,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '12',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            37 => 
            array (
                'id' => 38,
                'core_firms_id' => NULL,
                'workplan_category' => 9,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            38 => 
            array (
                'id' => 39,
                'core_firms_id' => NULL,
                'workplan_category' => 9,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_shifts',
                'value' => '8',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            39 => 
            array (
                'id' => 40,
                'core_firms_id' => NULL,
                'workplan_category' => 9,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'piece',
                'period' => 'week',
                'value' => '2',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            40 => 
            array (
                'id' => 41,
                'core_firms_id' => NULL,
                'workplan_category' => 9,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'uninterrupted_hours',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            41 => 
            array (
                'id' => 42,
                'core_firms_id' => NULL,
                'workplan_category' => 10,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '12',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            42 => 
            array (
                'id' => 43,
                'core_firms_id' => NULL,
                'workplan_category' => 10,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            43 => 
            array (
                'id' => 44,
                'core_firms_id' => NULL,
                'workplan_category' => 10,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_shifts',
                'value' => '8',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            44 => 
            array (
                'id' => 45,
                'core_firms_id' => NULL,
                'workplan_category' => 10,
                'type' => 'workday',
                'operator' => 'maximum',
                'unit' => 'piece',
                'period' => 'between_rest_days',
                'value' => '6',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            45 => 
            array (
                'id' => 46,
                'core_firms_id' => NULL,
                'workplan_category' => 10,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'sunday',
                'period' => 'month',
                'value' => '1',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            46 => 
            array (
                'id' => 47,
                'core_firms_id' => NULL,
                'workplan_category' => 11,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '12',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            47 => 
            array (
                'id' => 48,
                'core_firms_id' => NULL,
                'workplan_category' => 11,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            48 => 
            array (
                'id' => 49,
                'core_firms_id' => NULL,
                'workplan_category' => 11,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_shifts',
                'value' => '8',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            49 => 
            array (
                'id' => 50,
                'core_firms_id' => NULL,
                'workplan_category' => 11,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'piece',
                'period' => 'week',
                'value' => '2',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            50 => 
            array (
                'id' => 51,
                'core_firms_id' => NULL,
                'workplan_category' => 11,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'uninterrupted_hours',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            51 => 
            array (
                'id' => 52,
                'core_firms_id' => NULL,
                'workplan_category' => 12,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '12',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            52 => 
            array (
                'id' => 53,
                'core_firms_id' => NULL,
                'workplan_category' => 12,
                'type' => 'working_hours',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            53 => 
            array (
                'id' => 54,
                'core_firms_id' => NULL,
                'workplan_category' => 12,
                'type' => 'rest_period',
                'operator' => 'minimum',
                'unit' => 'hour',
                'period' => 'between_shifts',
                'value' => '8',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            54 => 
            array (
                'id' => 55,
                'core_firms_id' => NULL,
                'workplan_category' => 12,
                'type' => 'workday',
                'operator' => 'maximum',
                'unit' => 'piece',
                'period' => 'between_rest_days',
                'value' => '6',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            55 => 
            array (
                'id' => 56,
                'core_firms_id' => NULL,
                'workplan_category' => 12,
                'type' => 'rest_day',
                'operator' => 'minimum',
                'unit' => 'sunday',
                'period' => 'month',
                'value' => '1',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            56 => 
            array (
                'id' => 57,
                'core_firms_id' => NULL,
                'workplan_category' => NULL,
                'type' => 'overtimes',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '12',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            57 => 
            array (
                'id' => 58,
                'core_firms_id' => NULL,
                'workplan_category' => 4,
                'type' => 'overtimes',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'day',
                'value' => '24',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            58 => 
            array (
                'id' => 59,
                'core_firms_id' => NULL,
                'workplan_category' => NULL,
                'type' => 'overtimes',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '48',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            59 => 
            array (
                'id' => 60,
                'core_firms_id' => NULL,
                'workplan_category' => 4,
                'type' => 'overtimes',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'week',
                'value' => '72',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            60 => 
            array (
                'id' => 61,
                'core_firms_id' => NULL,
                'workplan_category' => NULL,
                'type' => 'overtimes',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'year',
                'value' => '250',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            61 => 
            array (
                'id' => 62,
                'core_firms_id' => NULL,
                'workplan_category' => NULL,
                'type' => 'standby',
                'operator' => 'maximum',
                'unit' => 'hour',
                'period' => 'month',
                'value' => '168',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
            62 => 
            array (
                'id' => 63,
                'core_firms_id' => NULL,
                'workplan_category' => NULL,
                'type' => 'standby',
                'operator' => 'maximum',
                'unit' => 'rest_day',
                'period' => 'month',
                'value' => '4',
                'base_rule' => 1,
                'prev_version_id' => NULL,
                'validity_start' => '1970-01-01 00:00:00',
                'validity_end' => NULL,
                'created_at' => '2024-03-18 14:42:38',
                'updated_at' => '2024-03-18 14:42:38',
            ),
        ));

        
    }
}