<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CoreEmailNotificationTypesTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('core_email_notification_types')->truncate();
        
        \DB::table('core_email_notification_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'type' => 1,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_1_worker',
            ),
            1 => 
            array (
                'id' => 2,
                'type' => 2,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_2_worker',
            ),
            2 => 
            array (
                'id' => 3,
                'type' => 3,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_3_worker',
            ),
            3 => 
            array (
                'id' => 4,
                'type' => 3,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_3_boss',
            ),
            4 => 
            array (
                'id' => 5,
                'type' => 4,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_4_worker',
            ),
            5 => 
            array (
                'id' => 6,
                'type' => 4,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_4_boss',
            ),
            6 => 
            array (
                'id' => 7,
                'type' => 5,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_5_worker',
            ),
            7 => 
            array (
                'id' => 8,
                'type' => 5,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_5_boss',
            ),
            8 => 
            array (
                'id' => 9,
                'type' => 6,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_6_worker',
            ),
            9 => 
            array (
                'id' => 10,
                'type' => 6,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_6_boss',
            ),
            10 => 
            array (
                'id' => 11,
                'type' => 7,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_7_worker',
            ),
            11 => 
            array (
                'id' => 12,
                'type' => 7,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_7_boss',
            ),
            12 => 
            array (
                'id' => 13,
                'type' => 8,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_8_worker',
            ),
            13 => 
            array (
                'id' => 14,
                'type' => 8,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_8_boss',
            ),
            14 => 
            array (
                'id' => 15,
                'type' => 9,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_9_worker',
            ),
            15 => 
            array (
                'id' => 16,
                'type' => 9,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_9_boss',
            ),
            16 => 
            array (
                'id' => 17,
                'type' => 10,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_10_worker',
            ),
            17 => 
            array (
                'id' => 18,
                'type' => 10,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_10_boss',
            ),
            18 => 
            array (
                'id' => 19,
                'type' => 11,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_11_worker',
            ),
            19 => 
            array (
                'id' => 20,
                'type' => 11,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_11_boss',
            ),
            20 => 
            array (
                'id' => 21,
                'type' => 12,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_12_worker',
            ),
            21 => 
            array (
                'id' => 22,
                'type' => 12,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_12_boss',
            ),
            22 => 
            array (
                'id' => 23,
                'type' => 13,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_13_worker',
            ),
            23 => 
            array (
                'id' => 24,
                'type' => 13,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_13_boss',
            ),
            24 => 
            array (
                'id' => 25,
                'type' => 14,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_14_worker',
            ),
            25 => 
            array (
                'id' => 26,
                'type' => 14,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_14_boss',
            ),
            26 => 
            array (
                'id' => 27,
                'type' => 15,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_15_worker',
            ),
            27 => 
            array (
                'id' => 28,
                'type' => 15,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_15_boss',
            ),
            28 => 
            array (
                'id' => 29,
                'type' => 16,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_16_worker',
            ),
            29 => 
            array (
                'id' => 30,
                'type' => 16,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_16_boss',
            ),
            30 => 
            array (
                'id' => 31,
                'type' => 17,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_17_worker',
            ),
            31 => 
            array (
                'id' => 32,
                'type' => 17,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_17_boss',
            ),
            32 => 
            array (
                'id' => 33,
                'type' => 18,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_18_worker',
            ),
            33 => 
            array (
                'id' => 34,
                'type' => 19,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_19_worker',
            ),
            34 => 
            array (
                'id' => 35,
                'type' => 20,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_20_worker',
            ),
            35 => 
            array (
                'id' => 36,
                'type' => 21,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_21_worker',
            ),
            36 => 
            array (
                'id' => 37,
                'type' => 22,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_22_worker',
            ),
            37 => 
            array (
                'id' => 38,
                'type' => 23,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_23_worker',
            ),
            38 => 
            array (
                'id' => 39,
                'type' => 24,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_24_worker',
            ),
            39 => 
            array (
                'id' => 40,
                'type' => 25,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_25_worker',
            ),
            40 => 
            array (
                'id' => 41,
                'type' => 26,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_26_worker',
            ),
            41 => 
            array (
                'id' => 42,
                'type' => 27,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_27_worker',
            ),
            42 => 
            array (
                'id' => 43,
                'type' => 27,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_27_boss',
            ),
            43 => 
            array (
                'id' => 44,
                'type' => 28,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_28_worker',
            ),
            44 => 
            array (
                'id' => 45,
                'type' => 28,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_28_boss',
            ),
            45 => 
            array (
                'id' => 46,
                'type' => 29,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_29_worker',
            ),
            46 => 
            array (
                'id' => 47,
                'type' => 29,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_29_boss',
            ),
            47 => 
            array (
                'id' => 48,
                'type' => 30,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_30_worker',
            ),
            48 => 
            array (
                'id' => 49,
                'type' => 31,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_31_worker',
            ),
            49 => 
            array (
                'id' => 50,
                'type' => 32,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_32_worker',
            ),
            50 => 
            array (
                'id' => 51,
                'type' => 32,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_32_boss',
            ),
            51 => 
            array (
                'id' => 52,
                'type' => 33,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_33_worker',
            ),
            52 => 
            array (
                'id' => 53,
                'type' => 33,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_33_boss',
            ),
            53 => 
            array (
                'id' => 54,
                'type' => 34,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_34_worker',
            ),
            54 => 
            array (
                'id' => 55,
                'type' => 34,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_34_boss',
            ),
            55 => 
            array (
                'id' => 56,
                'type' => 35,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_35_worker',
            ),
            56 => 
            array (
                'id' => 57,
                'type' => 35,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_35_boss',
            ),
            57 => 
            array (
                'id' => 58,
                'type' => 36,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_36_worker',
            ),
            58 => 
            array (
                'id' => 59,
                'type' => 36,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_36_boss',
            ),
            59 => 
            array (
                'id' => 60,
                'type' => 37,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_37_worker',
            ),
            60 => 
            array (
                'id' => 61,
                'type' => 37,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_37_boss',
            ),
            61 => 
            array (
                'id' => 62,
                'type' => 38,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_38_worker',
            ),
            62 => 
            array (
                'id' => 63,
                'type' => 38,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_38_boss',
            ),
            63 => 
            array (
                'id' => 64,
                'type' => 39,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_39_worker',
            ),
            64 => 
            array (
                'id' => 65,
                'type' => 39,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_39_boss',
            ),
            65 => 
            array (
                'id' => 66,
                'type' => 40,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_40_worker',
            ),
            66 => 
            array (
                'id' => 67,
                'type' => 40,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_40_boss',
            ),
            67 => 
            array (
                'id' => 68,
                'type' => 41,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_9_worker',
            ),
            68 => 
            array (
                'id' => 69,
                'type' => 42,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_42_worker',
            ),
            69 => 
            array (
                'id' => 70,
                'type' => 42,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_42_boss',
            ),
            70 => 
            array (
                'id' => 71,
                'type' => 43,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_43_boss',
            ),
            71 => 
            array (
                'id' => 72,
                'type' => 44,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_44_boss',
            ),
            72 => 
            array (
                'id' => 73,
                'type' => 45,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_45_boss',
            ),
            73 => 
            array (
                'id' => 74,
                'type' => 46,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_46_boss',
            ),
            74 => 
            array (
                'id' => 75,
                'type' => 47,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_47_boss',
            ),
            75 => 
            array (
                'id' => 76,
                'type' => 48,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_48_boss',
            ),
            76 => 
            array (
                'id' => 77,
                'type' => 49,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_49_worker',
            ),
            77 => 
            array (
                'id' => 78,
                'type' => 49,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_49_boss',
            ),
            78 => 
            array (
                'id' => 79,
                'type' => 50,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_50_worker',
            ),
            79 => 
            array (
                'id' => 80,
                'type' => 50,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_50_boss',
            ),
            80 => 
            array (
                'id' => 81,
                'type' => 51,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_51_worker',
            ),
            81 => 
            array (
                'id' => 82,
                'type' => 51,
                'subtype' => 1,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_51_boss',
            ),
            82 => 
            array (
                'id' => 83,
                'type' => 52,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_52_worker',
            ),
            83 => 
            array (
                'id' => 84,
                'type' => 52,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_52_boss',
            ),
            84 => 
            array (
                'id' => 85,
                'type' => 53,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_53_worker',
            ),
            85 => 
            array (
                'id' => 86,
                'type' => 53,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_53_boss',
            ),
            86 => 
            array (
                'id' => 87,
                'type' => 54,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_54_worker',
            ),
            87 => 
            array (
                'id' => 88,
                'type' => 54,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_54_boss',
            ),
            88 => 
            array (
                'id' => 89,
                'type' => 55,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_55_administrator',
            ),
            89 => 
            array (
                'id' => 90,
                'type' => 56,
                'subtype' => 0,
                'extra_notification' => 0,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_56_administrator',
            ),
            90 => 
            array (
                'id' => 91,
                'type' => 57,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_57_worker',
            ),
            91 => 
            array (
                'id' => 92,
                'type' => 57,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_57_boss',
            ),
            92 => 
            array (
                'id' => 93,
                'type' => 58,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_58_worker',
            ),
            93 => 
            array (
                'id' => 94,
                'type' => 58,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_58_boss',
            ),
            94 => 
            array (
                'id' => 95,
                'type' => 59,
                'subtype' => 0,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_59_worker',
            ),
            95 => 
            array (
                'id' => 96,
                'type' => 59,
                'subtype' => 1,
                'extra_notification' => 1,
                'core_firms_id' => 1,
                'is_combined' => 0,
                'display' => 1,
                'expiration_unit' => NULL,
                'expiration_values' => NULL,
                'timing_time' => NULL,
                'template' => 'email_notification_59_boss',
            ),
        ));

        
    }
}