<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CoreMenuItemsTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('core_menu_items')->truncate();
        
        \DB::table('core_menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'core_modules_id' => 1,
                'route' => '',
                'parent' => 0,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'core_modules_id' => 1,
                'route' => 'core_persons_personal_profile_showPersonalProfile',
                'parent' => 1,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'core_modules_id' => 1,
                'route' => 'core_index_index_dashboard',
                'parent' => 1,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'core_modules_id' => 1,
                'route' => 'core_index_index_selectLegalEntity',
                'parent' => 1,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'core_modules_id' => 1,
                'route' => '',
                'parent' => 0,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'core_modules_id' => 1,
                'route' => 'core_index_login_logout',
                'parent' => 1,
                '_order' => 5,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'core_modules_id' => 2,
                'route' => '',
                'parent' => 0,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'core_modules_id' => 2,
                'route' => 'core_persons_persons_index',
                'parent' => 7,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'core_modules_id' => 3,
                'route' => 'core_log_log_index',
                'parent' => 5,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'core_modules_id' => 5,
                'route' => '',
                'parent' => 0,
                '_order' => 5,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'core_modules_id' => 5,
                'route' => 'core_permissions_permissions_index',
                'parent' => 10,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'core_modules_id' => 4,
                'route' => 'core_parameters_parameters_index',
                'parent' => 5,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'core_modules_id' => 1,
                'route' => '',
                'parent' => 0,
                '_order' => 4,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'core_modules_id' => 6,
                'route' => '',
                'parent' => 13,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'core_modules_id' => 6,
                'route' => 'core_attributes_person_or_legal_entity_attributes_showPersonAttributes',
                'parent' => 14,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'core_modules_id' => 6,
                'route' => 'core_attributes_person_or_legal_entity_attributes_showLegalEntityAttributes',
                'parent' => 14,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'core_modules_id' => 7,
                'route' => 'attendance_bonuses_bonuses_index',
                'parent' => 13,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'core_modules_id' => 8,
                'route' => 'attendance_shifts_shifts_index',
                'parent' => 13,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'core_modules_id' => 9,
                'route' => 'core_establishments_index',
                'parent' => 13,
                '_order' => 4,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'core_modules_id' => 10,
                'route' => 'core_departments_index',
                'parent' => 13,
                '_order' => 5,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'core_modules_id' => 11,
                'route' => 'core_cost_centers_index',
                'parent' => 13,
                '_order' => 6,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'core_modules_id' => 12,
                'route' => 'core_permissiongroups_permissiongroups_index',
                'parent' => 10,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'core_modules_id' => 13,
                'route' => 'core_legalentities_legalentities_legalentityreopenindex',
                'parent' => 7,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'core_modules_id' => 14,
                'route' => 'core_hierarchy_hierarchy_index',
                'parent' => 10,
                '_order' => 4,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'core_modules_id' => 15,
                'route' => 'core_extraemailaddresses_extraemailaddresses_index',
                'parent' => 7,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'core_modules_id' => 16,
                'route' => 'core_holidays_holidays_index',
                'parent' => 5,
                '_order' => 4,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'core_modules_id' => 2,
                'route' => 'core_persons_persons_resetPasswordIndex',
                'parent' => 5,
                '_order' => 5,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'core_modules_id' => 17,
                'route' => 'core_substitutions_substitutions_index',
                'parent' => 1,
                '_order' => 4,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 0,
                'visible_for_substitution' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'core_modules_id' => 1,
                'route' => '',
                'parent' => 5,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'core_modules_id' => 18,
                'route' => 'core_email_notifications_email_notifications_index',
                'parent' => 29,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'core_modules_id' => 18,
                'route' => 'core_email_notifications_email_notifications_editemailtypeindex',
                'parent' => 29,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'core_modules_id' => 19,
                'route' => 'attendance_offdaytypes_offdaytypes_index',
                'parent' => 29,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            32 => 
            array (
                'id' => 33,
                'core_modules_id' => 19,
                'route' => 'attendance_offdaytypes_offdaytypes_orderIndex',
                'parent' => 29,
                '_order' => 4,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'core_modules_id' => 20,
                'route' => 'attendance_attendancesheets_attendancesheets_index',
                'parent' => 7,
                '_order' => 4,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'core_modules_id' => 21,
                'route' => 'attendance_workplans_workplans_index',
                'parent' => 42,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'core_modules_id' => 22,
                'route' => 'attendance_rounding_settings_rounding_settings_index',
                'parent' => 29,
                '_order' => 6,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            36 => 
            array (
                'id' => 37,
                'core_modules_id' => 23,
                'route' => 'attendance_places_of_work_places_of_work_index',
                'parent' => 13,
                '_order' => 8,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            37 => 
            array (
                'id' => 38,
                'core_modules_id' => 24,
                'route' => 'attendance_abscences_abscences_index',
                'parent' => 7,
                '_order' => 4,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            38 => 
            array (
                'id' => 39,
                'core_modules_id' => 25,
                'route' => '',
                'parent' => 5,
                '_order' => 6,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            39 => 
            array (
                'id' => 40,
                'core_modules_id' => 25,
                'route' => 'core_import_import_index',
                'parent' => 39,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            40 => 
            array (
                'id' => 41,
                'core_modules_id' => 26,
                'route' => 'attendance_attendancesheetsettings_attendancesheetsettings_index',
                'parent' => 29,
                '_order' => 6,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            41 => 
            array (
                'id' => 42,
                'core_modules_id' => 21,
                'route' => '',
                'parent' => 13,
                '_order' => 7,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            42 => 
            array (
                'id' => 43,
                'core_modules_id' => 21,
                'route' => 'attendance_workplans_workplan_batch_assignment',
                'parent' => 42,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            43 => 
            array (
                'id' => 44,
                'core_modules_id' => 21,
                'route' => 'attendance_workplans_workplans_showVerificationConditions',
                'parent' => 42,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            44 => 
            array (
                'id' => 45,
                'core_modules_id' => 27,
                'route' => 'attendance_payrollsheets_payrollsheets_index',
                'parent' => 1,
                '_order' => 6,
                'core_parameters_id' => 22,
                'core_parameters_value' => '6',
                'visible_for_outsourced_admin' => 0,
                'visible_for_substitution' => 0,
            ),
            45 => 
            array (
                'id' => 46,
                'core_modules_id' => 28,
                'route' => 'core_specialpersonstatuses_specialpersonstatuses_index',
                'parent' => 7,
                '_order' => 5,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            46 => 
            array (
                'id' => 47,
                'core_modules_id' => 29,
                'route' => '',
                'parent' => 7,
                '_order' => 7,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            47 => 
            array (
                'id' => 48,
                'core_modules_id' => 29,
                'route' => 'attendance_worktimelimits_index',
                'parent' => 47,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            48 => 
            array (
                'id' => 49,
                'core_modules_id' => 29,
                'route' => 'attendance_worktimelimits_assignments',
                'parent' => 47,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            49 => 
            array (
                'id' => 50,
                'core_modules_id' => 30,
                'route' => 'core_leavers_leavers_index',
                'parent' => 7,
                '_order' => 8,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            50 => 
            array (
                'id' => 51,
                'core_modules_id' => 20,
                'route' => 'attendance_attendancesheetsettings_attendancesheetexportsettings_index',
                'parent' => 29,
                '_order' => 7,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            51 => 
            array (
                'id' => 52,
                'core_modules_id' => 31,
                'route' => 'core_otherincomes_otherincomes_index',
                'parent' => 13,
                '_order' => 9,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 0,
                'visible_for_substitution' => 0,
            ),
            52 => 
            array (
                'id' => 53,
                'core_modules_id' => 32,
                'route' => 'core_specialpermissions_specialpermissions_index',
                'parent' => 10,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            53 => 
            array (
                'id' => 54,
                'core_modules_id' => 33,
                'route' => 'attendance_overtimeordination_overtimeordination_index',
                'parent' => 7,
                '_order' => 9,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            54 => 
            array (
                'id' => 55,
                'core_modules_id' => 34,
                'route' => 'attendance_abscencetypes_abscencetypes_index',
                'parent' => 29,
                '_order' => 8,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            55 => 
            array (
                'id' => 56,
                'core_modules_id' => 6,
                'route' => 'core_attributes_person_or_legal_entity_attributes_showCarriedBalances',
                'parent' => 7,
                '_order' => 10,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            56 => 
            array (
                'id' => 57,
                'core_modules_id' => 35,
                'route' => 'attendance_batchconfirmations_batchconfirmations_index',
                'parent' => 7,
                '_order' => 10,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            57 => 
            array (
                'id' => 58,
                'core_modules_id' => 13,
                'route' => 'core_legalentities_legalentities_legalEntityRenameForm',
                'parent' => 7,
                '_order' => 12,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            58 => 
            array (
                'id' => 59,
                'core_modules_id' => 36,
                'route' => 'core_export_export_index',
                'parent' => 39,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            59 => 
            array (
                'id' => 60,
                'core_modules_id' => 37,
                'route' => 'attendance_scheduleplanner_scheduleplanner_index',
                'parent' => 7,
                '_order' => 13,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            60 => 
            array (
                'id' => 61,
                'core_modules_id' => 20,
                'route' => 'attendance_attendancesheets_attendancesheetsexport_attendancesheetsxlsexportindex',
                'parent' => 65,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            61 => 
            array (
                'id' => 62,
                'core_modules_id' => 38,
                'route' => 'core_reporter_reporter_index',
                'parent' => 7,
                '_order' => 15,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            62 => 
            array (
                'id' => 63,
                'core_modules_id' => 39,
                'route' => 'attendance_abscenceplanner_abscenceplanner_index',
                'parent' => 7,
                '_order' => 16,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            63 => 
            array (
                'id' => 64,
                'core_modules_id' => 40,
                'route' => 'attendance_offdaytypelimit_offdaytypelimit_index',
                'parent' => 7,
                '_order' => 17,
                'core_parameters_id' => 8,
                'core_parameters_value' => '11',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            64 => 
            array (
                'id' => 65,
                'core_modules_id' => 20,
                'route' => '',
                'parent' => 7,
                '_order' => 18,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            65 => 
            array (
                'id' => 66,
                'core_modules_id' => 20,
                'route' => 'attendance_attendancesheets_attendancesheetsexport_attendancesheetspdfexportindex',
                'parent' => 65,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            66 => 
            array (
                'id' => 67,
                'core_modules_id' => 41,
                'route' => '',
                'parent' => 7,
                '_order' => 19,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            67 => 
            array (
                'id' => 68,
                'core_modules_id' => 41,
                'route' => 'attendance_legalstock_legalstock_classification',
                'parent' => 67,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            68 => 
            array (
                'id' => 69,
                'core_modules_id' => 41,
                'route' => 'attendance_legalstock_legalstock_changeClassification',
                'parent' => 67,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            69 => 
            array (
                'id' => 70,
                'core_modules_id' => 33,
                'route' => 'attendance_overtimeordination_overtimeordination_deleteOvertimes',
                'parent' => 7,
                '_order' => 9,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            70 => 
            array (
                'id' => 71,
                'core_modules_id' => 42,
                'route' => '',
                'parent' => 7,
                '_order' => 20,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            71 => 
            array (
                'id' => 72,
                'core_modules_id' => 42,
                'route' => 'attendance_fulldaybonus_fulldaybonus_order_form',
                'parent' => 71,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            72 => 
            array (
                'id' => 73,
                'core_modules_id' => 42,
                'route' => 'attendance_fulldaybonus_fulldaybonus_delete_form',
                'parent' => 71,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            73 => 
            array (
                'id' => 74,
                'core_modules_id' => 25,
                'route' => 'core_import_abscences_import_index',
                'parent' => 29,
                '_order' => 5,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            74 => 
            array (
                'id' => 75,
                'core_modules_id' => 43,
                'route' => 'attendance_standbytypes_standbytypes_index',
                'parent' => 13,
                '_order' => 10,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            75 => 
            array (
                'id' => 76,
                'core_modules_id' => 44,
                'route' => 'core_profitcenters_profitcenters_index',
                'parent' => 13,
                '_order' => 11,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            76 => 
            array (
                'id' => 77,
                'core_modules_id' => 24,
                'route' => 'attendance_abscences_abscences_show_delete_batch',
                'parent' => 7,
                '_order' => 4,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            77 => 
            array (
                'id' => 78,
                'core_modules_id' => 43,
                'route' => 'attendance_standbytypes_standby_batch_assignment',
                'parent' => 7,
                '_order' => 21,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            78 => 
            array (
                'id' => 79,
                'core_modules_id' => 36,
                'route' => 'core_export_export_sap_data',
                'parent' => 39,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            79 => 
            array (
                'id' => 80,
                'core_modules_id' => 36,
                'route' => 'core_export_show_worktime_justification',
                'parent' => 39,
                '_order' => 4,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            80 => 
            array (
                'id' => 81,
                'core_modules_id' => 36,
                'route' => 'core_export_workday_division_export',
                'parent' => 39,
                '_order' => 6,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            81 => 
            array (
                'id' => 82,
                'core_modules_id' => 36,
                'route' => 'core_export_show_worktime_statement',
                'parent' => 39,
                '_order' => 5,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 0,
                'visible_for_substitution' => 0,
            ),
            82 => 
            array (
                'id' => 85,
                'core_modules_id' => 29,
                'route' => 'attendance_worktimelimit_batch_deletion',
                'parent' => 47,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            83 => 
            array (
                'id' => 86,
                'core_modules_id' => 2,
                'route' => 'core_persons_persons_forcedPasswordRefreshment',
                'parent' => 5,
                '_order' => 5,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            84 => 
            array (
                'id' => 87,
                'core_modules_id' => 48,
                'route' => 'attendance_workdaydivision_workdaydivision_sorting',
                'parent' => 29,
                '_order' => 9,
                'core_parameters_id' => NULL,
                'core_parameters_value' => 'null',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            85 => 
            array (
                'id' => 88,
                'core_modules_id' => 48,
                'route' => 'attendance_workdaydivision_workdaydivision_index',
                'parent' => 13,
                '_order' => 12,
                'core_parameters_id' => NULL,
                'core_parameters_value' => 'null',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            86 => 
            array (
                'id' => 89,
                'core_modules_id' => 3,
                'route' => 'core_log_log_downloadLogFiles',
                'parent' => 5,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            87 => 
            array (
                'id' => 90,
                'core_modules_id' => 48,
                'route' => 'attendance_workdaydivision_workdaydivision_export_setting',
                'parent' => 29,
                '_order' => 10,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            88 => 
            array (
                'id' => 91,
                'core_modules_id' => 14,
                'route' => 'core_hierarchy_hierarchy_cleanerIndex',
                'parent' => 10,
                '_order' => 5,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            89 => 
            array (
                'id' => 92,
                'core_modules_id' => 29,
                'route' => '',
                'parent' => 47,
                '_order' => 4,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            90 => 
            array (
                'id' => 93,
                'core_modules_id' => 49,
                'route' => 'attendance_documenthandler_documenthandler_index',
                'parent' => 1,
                '_order' => 6,
                'core_parameters_id' => 65,
                'core_parameters_value' => '6',
                'visible_for_outsourced_admin' => 0,
                'visible_for_substitution' => 0,
            ),
            91 => 
            array (
                'id' => 94,
                'core_modules_id' => 50,
                'route' => 'attendance_documentuploader_documentuploader_index',
                'parent' => 5,
                '_order' => 7,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            92 => 
            array (
                'id' => 95,
                'core_modules_id' => 18,
                'route' => 'core_email_notifications_email_notifications_wrongEmailNotificationsIndex',
                'parent' => 29,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            93 => 
            array (
                'id' => 96,
                'core_modules_id' => 51,
                'route' => 'attendance_scheduler_scheduler_index',
                'parent' => 7,
                '_order' => 13,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            94 => 
            array (
                'id' => 97,
                'core_modules_id' => 20,
                'route' => 'attendance_attendancesheets_attendancesheetsexport_attendanceSheetAllDetailsExport',
                'parent' => 65,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            95 => 
            array (
                'id' => 98,
                'core_modules_id' => 52,
                'route' => 'core_aggregate_surface_notifications',
                'parent' => 1,
                '_order' => 3,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            96 => 
            array (
                'id' => 99,
                'core_modules_id' => 53,
                'route' => '',
                'parent' => 7,
                '_order' => 22,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            97 => 
            array (
                'id' => 100,
                'core_modules_id' => 56,
                'route' => 'attendance_entity_selector_settings_index',
                'parent' => 29,
                '_order' => 11,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            98 => 
            array (
                'id' => 101,
                'core_modules_id' => 53,
                'route' => 'attendance_holidayrules_holidayrules_index',
                'parent' => 99,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            99 => 
            array (
                'id' => 102,
                'core_modules_id' => 53,
                'route' => 'attendance_holidayrules_holidayrules_addLegalEntities',
                'parent' => 99,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            100 => 
            array (
                'id' => 103,
                'core_modules_id' => 1,
                'route' => '',
                'parent' => 0,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            101 => 
            array (
                'id' => 104,
                'core_modules_id' => 58,
                'route' => 'core_pekseg_uzletek',
                'parent' => 103,
                '_order' => 1,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
            102 => 
            array (
                'id' => 105,
                'core_modules_id' => 57,
                'route' => 'core_pekseg_dolgozok',
                'parent' => 103,
                '_order' => 2,
                'core_parameters_id' => NULL,
                'core_parameters_value' => '',
                'visible_for_outsourced_admin' => 1,
                'visible_for_substitution' => 1,
            ),
        ));

        
    }
}