<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CoreLegalEntitiesAttributesTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('core_legal_entities_attributes')->truncate();
        
        \DB::table('core_legal_entities_attributes')->insert(array (
            0 => 
            array (
                'id' => 1,
                'type' => 'varchar',
                'system' => 1,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 1,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:21',
                'updated_at' => '2024-03-18 14:42:21',
            ),
            1 => 
            array (
                'id' => 2,
                'type' => 'int',
                'system' => 2,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:21',
                'updated_at' => '2024-03-18 14:42:21',
            ),
            2 => 
            array (
                'id' => 3,
                'type' => 'int',
                'system' => 3,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:21',
                'updated_at' => '2024-03-18 14:42:21',
            ),
            3 => 
            array (
                'id' => 4,
                'type' => 'int',
                'system' => 4,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 1,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:21',
                'updated_at' => '2024-03-18 14:42:21',
            ),
            4 => 
            array (
                'id' => 5,
                'type' => 'tinyint',
                'system' => 5,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 1,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:21',
                'updated_at' => '2024-03-18 14:42:21',
            ),
            5 => 
            array (
                'id' => 6,
                'type' => 'tinyint',
                'system' => 6,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 1,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:21',
                'updated_at' => '2024-03-18 14:42:21',
            ),
            6 => 
            array (
                'id' => 7,
                'type' => 'date',
                'system' => 7,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:21',
                'updated_at' => '2024-03-18 14:42:21',
            ),
            7 => 
            array (
                'id' => 8,
                'type' => 'date',
                'system' => 8,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 1,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 0,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:21',
                'updated_at' => '2024-03-18 14:42:21',
            ),
            8 => 
            array (
                'id' => 9,
                'type' => 'date',
                'system' => 9,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 0,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:21',
                'updated_at' => '2024-03-18 14:42:21',
            ),
            9 => 
            array (
                'id' => 10,
                'type' => 'int',
                'system' => 10,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:22',
                'updated_at' => '2024-03-18 14:42:22',
            ),
            10 => 
            array (
                'id' => 11,
                'type' => 'int',
                'system' => 11,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:22',
                'updated_at' => '2024-03-18 14:42:22',
            ),
            11 => 
            array (
                'id' => 12,
                'type' => 'int',
                'system' => 12,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:22',
                'updated_at' => '2024-03-18 14:42:22',
            ),
            12 => 
            array (
                'id' => 13,
                'type' => 'tinyint',
                'system' => 13,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:22',
                'updated_at' => '2024-03-18 14:42:22',
            ),
            13 => 
            array (
                'id' => 14,
                'type' => 'date',
                'system' => 14,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 0,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:23',
                'updated_at' => '2024-03-18 14:42:23',
            ),
            14 => 
            array (
                'id' => 15,
                'type' => 'varchar',
                'system' => 15,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 0,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:23',
                'updated_at' => '2024-03-18 14:42:23',
            ),
            15 => 
            array (
                'id' => 16,
                'type' => 'tinyint',
                'system' => 16,
                'core_firms_id' => 0,
                'visible_for_owner' => 0,
                'visible_for_boss' => 0,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:23',
                'updated_at' => '2024-03-18 14:42:23',
            ),
            16 => 
            array (
                'id' => 17,
                'type' => 'varchar',
                'system' => 17,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 1,
                'editable_for_owner' => 0,
                'editable_for_boss' => 1,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 0,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:28',
                'updated_at' => '2024-03-18 14:42:29',
            ),
            17 => 
            array (
                'id' => 18,
                'type' => 'tinyint',
                'system' => 18,
                'core_firms_id' => 0,
                'visible_for_owner' => 0,
                'visible_for_boss' => 0,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:29',
                'updated_at' => '2024-03-18 14:42:29',
            ),
            18 => 
            array (
                'id' => 19,
                'type' => 'int',
                'system' => 19,
                'core_firms_id' => 0,
                'visible_for_owner' => 0,
                'visible_for_boss' => 0,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:30',
                'updated_at' => '2024-03-18 14:42:30',
            ),
            19 => 
            array (
                'id' => 20,
                'type' => 'tinyint',
                'system' => 20,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:30',
                'updated_at' => '2024-03-18 14:42:30',
            ),
        ));

        
    }
}