<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CorePersonsAttributesTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('core_persons_attributes')->truncate();
        
        \DB::table('core_persons_attributes')->insert(array (
            0 => 
            array (
                'id' => 1,
                'type' => 'varchar',
                'system' => 1,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 1,
                'value_email' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:14',
                'updated_at' => '2024-03-18 14:42:14',
            ),
            1 => 
            array (
                'id' => 2,
                'type' => 'varchar',
                'system' => 2,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 1,
                'value_email' => 1,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:14',
                'updated_at' => '2024-03-18 14:42:14',
            ),
            2 => 
            array (
                'id' => 3,
                'type' => 'varchar',
                'system' => 3,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 1,
                'value_email' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:14',
                'updated_at' => '2024-03-18 14:42:14',
            ),
            3 => 
            array (
                'id' => 4,
                'type' => 'varchar',
                'system' => 4,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 1,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_email' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:14',
                'updated_at' => '2024-03-18 14:42:14',
            ),
            4 => 
            array (
                'id' => 5,
                'type' => 'varchar',
                'system' => 5,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 0,
                'visible_for_other' => 0,
                'editable_for_owner' => 1,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_email' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:14',
                'updated_at' => '2024-03-18 14:42:14',
            ),
            5 => 
            array (
                'id' => 6,
                'type' => 'tinyint',
                'system' => 6,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 1,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_email' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:14',
                'updated_at' => '2024-03-18 14:42:14',
            ),
            6 => 
            array (
                'id' => 7,
                'type' => 'int',
                'system' => 7,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 1,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_email' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:14',
                'updated_at' => '2024-03-18 14:42:14',
            ),
            7 => 
            array (
                'id' => 8,
                'type' => 'tinyint',
                'system' => 8,
                'core_firms_id' => 0,
                'visible_for_owner' => 0,
                'visible_for_boss' => 0,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_email' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:22',
                'updated_at' => '2024-03-18 14:42:22',
            ),
            8 => 
            array (
                'id' => 9,
                'type' => 'varchar',
                'system' => 9,
                'core_firms_id' => 0,
                'visible_for_owner' => 1,
                'visible_for_boss' => 1,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 1,
                'value_email' => 0,
                'value_regex' => '^8[0-9]{9}$',
                'created_at' => '2024-03-18 14:42:25',
                'updated_at' => '2024-03-18 14:42:25',
            ),
            9 => 
            array (
                'id' => 10,
                'type' => 'date',
                'system' => 10,
                'core_firms_id' => 0,
                'visible_for_owner' => 0,
                'visible_for_boss' => 0,
                'visible_for_other' => 0,
                'editable_for_owner' => 0,
                'editable_for_boss' => 0,
                'editable_for_other' => 0,
                'visible_in_header' => 0,
                'deadline_if_required' => '1000-01-01 00:00:00',
                'value_required' => 1,
                'value_unique' => 0,
                'value_email' => 0,
                'value_regex' => '',
                'created_at' => '2024-03-18 14:42:25',
                'updated_at' => '2024-03-18 14:42:25',
            ),
        ));

        
    }
}