<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CoreActionsTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('core_actions')->truncate();
        
        \DB::table('core_actions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 1,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'core_menu_items_id' => 4,
                'core_modules_id' => 1,
                'name' => 'selectLegalEntity',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 1,
                'name' => 'setLegalEntity',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'core_menu_items_id' => 3,
                'core_modules_id' => 1,
                'name' => 'dashboard',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 1,
                'name' => 'loginForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 1,
                'name' => 'login',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'core_menu_items_id' => 6,
                'core_modules_id' => 1,
                'name' => 'logout',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 1,
                'name' => 'forgotPasswordForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 1,
                'name' => 'forgotPasswordProcess',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 1,
                'name' => 'giveNewPassword',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'core_menu_items_id' => 9,
                'core_modules_id' => 3,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'core_menu_items_id' => 12,
                'core_modules_id' => 4,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'core_menu_items_id' => 2,
                'core_modules_id' => 2,
                'name' => 'showPersonalProfile',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'core_menu_items_id' => 12,
                'core_modules_id' => 4,
                'name' => 'saveParameter',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'core_menu_items_id' => 11,
                'core_modules_id' => 5,
                'name' => 'permissions',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'core_menu_items_id' => 15,
                'core_modules_id' => 6,
                'name' => 'showPersonAttributes',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'core_menu_items_id' => 16,
                'core_modules_id' => 6,
                'name' => 'showLegalEntityAttributes',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'core_menu_items_id' => 17,
                'core_modules_id' => 7,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'core_menu_items_id' => 18,
                'core_modules_id' => 8,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'core_menu_items_id' => 19,
                'core_modules_id' => 9,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'core_menu_items_id' => 20,
                'core_modules_id' => 10,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'core_menu_items_id' => 21,
                'core_modules_id' => 11,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'core_menu_items_id' => 8,
                'core_modules_id' => 2,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            23 => 
            array (
                'id' => 24,
                'core_menu_items_id' => 22,
                'core_modules_id' => 12,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'core_menu_items_id' => 23,
                'core_modules_id' => 13,
                'name' => 'legalEntityReOpenIndex',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'core_menu_items_id' => 24,
                'core_modules_id' => 14,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            26 => 
            array (
                'id' => 27,
                'core_menu_items_id' => 25,
                'core_modules_id' => 15,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            27 => 
            array (
                'id' => 28,
                'core_menu_items_id' => 26,
                'core_modules_id' => 16,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            28 => 
            array (
                'id' => 29,
                'core_menu_items_id' => 26,
                'core_modules_id' => 16,
                'name' => 'editHolidaysCalendar',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            29 => 
            array (
                'id' => 30,
                'core_menu_items_id' => 26,
                'core_modules_id' => 16,
                'name' => 'updateHolidaysCalendar',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'core_menu_items_id' => 27,
                'core_modules_id' => 2,
                'name' => 'resetPasswordIndex',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            31 => 
            array (
                'id' => 32,
                'core_menu_items_id' => 28,
                'core_modules_id' => 17,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'core_menu_items_id' => 28,
                'core_modules_id' => 17,
                'name' => 'getCreateForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'core_menu_items_id' => 28,
                'core_modules_id' => 17,
                'name' => 'deleteSubstitution',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            34 => 
            array (
                'id' => 35,
                'core_menu_items_id' => 30,
                'core_modules_id' => 18,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            35 => 
            array (
                'id' => 36,
                'core_menu_items_id' => 31,
                'core_modules_id' => 18,
                'name' => 'editemailtypeindex',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'core_menu_items_id' => 28,
                'core_modules_id' => 17,
                'name' => 'addSubstitution',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'core_menu_items_id' => 31,
                'core_modules_id' => 18,
                'name' => 'editemailtype',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'core_menu_items_id' => 31,
                'core_modules_id' => 18,
                'name' => 'saveemailtype',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            39 => 
            array (
                'id' => 40,
                'core_menu_items_id' => 32,
                'core_modules_id' => 19,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            40 => 
            array (
                'id' => 41,
                'core_menu_items_id' => 33,
                'core_modules_id' => 19,
                'name' => 'orderIndex',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'core_menu_items_id' => 33,
                'core_modules_id' => 19,
                'name' => 'saveOffdayOrder',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'core_menu_items_id' => 34,
                'core_modules_id' => 20,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'core_menu_items_id' => 35,
                'core_modules_id' => 21,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            44 => 
            array (
                'id' => 45,
                'core_menu_items_id' => 36,
                'core_modules_id' => 22,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            45 => 
            array (
                'id' => 46,
                'core_menu_items_id' => 36,
                'core_modules_id' => 22,
                'name' => 'setRoundingSetting',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            46 => 
            array (
                'id' => 47,
                'core_menu_items_id' => 35,
                'core_modules_id' => 21,
                'name' => 'showCreateForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            47 => 
            array (
                'id' => 48,
                'core_menu_items_id' => 35,
                'core_modules_id' => 21,
                'name' => 'showEditForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            48 => 
            array (
                'id' => 49,
                'core_menu_items_id' => 37,
                'core_modules_id' => 23,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            49 => 
            array (
                'id' => 50,
                'core_menu_items_id' => 37,
                'core_modules_id' => 23,
                'name' => 'editPlacesOfWork',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            50 => 
            array (
                'id' => 51,
                'core_menu_items_id' => 38,
                'core_modules_id' => 24,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            51 => 
            array (
                'id' => 52,
                'core_menu_items_id' => 40,
                'core_modules_id' => 25,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            52 => 
            array (
                'id' => 53,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 25,
                'name' => 'error',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            53 => 
            array (
                'id' => 54,
                'core_menu_items_id' => 40,
                'core_modules_id' => 25,
                'name' => 'processImport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            54 => 
            array (
                'id' => 55,
                'core_menu_items_id' => 41,
                'core_modules_id' => 26,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            55 => 
            array (
                'id' => 56,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 1,
                'name' => 'payrollSoftwareRequested',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            56 => 
            array (
                'id' => 57,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 1,
                'name' => 'payrollSoftwarePermitted',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            57 => 
            array (
                'id' => 58,
                'core_menu_items_id' => 43,
                'core_modules_id' => 21,
                'name' => 'showBatchAssignment',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            58 => 
            array (
                'id' => 59,
                'core_menu_items_id' => 44,
                'core_modules_id' => 21,
                'name' => 'showVerificationConditions',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            59 => 
            array (
                'id' => 60,
                'core_menu_items_id' => 35,
                'core_modules_id' => 21,
                'name' => 'exportWorkplan',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            60 => 
            array (
                'id' => 61,
                'core_menu_items_id' => 45,
                'core_modules_id' => 27,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            61 => 
            array (
                'id' => 62,
                'core_menu_items_id' => 45,
                'core_modules_id' => 27,
                'name' => 'getPayrollSheet',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            62 => 
            array (
                'id' => 63,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 1,
                'name' => 'electronicPayrollSheetNotEnabled',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            63 => 
            array (
                'id' => 64,
                'core_menu_items_id' => 43,
                'core_modules_id' => 21,
                'name' => 'exportBatchAssignment',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            64 => 
            array (
                'id' => 65,
                'core_menu_items_id' => 40,
                'core_modules_id' => 25,
                'name' => 'validateUploadedFile',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            65 => 
            array (
                'id' => 66,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 24,
                'name' => 'exportAbscencesOrdination',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            66 => 
            array (
                'id' => 67,
                'core_menu_items_id' => 40,
                'core_modules_id' => 25,
                'name' => 'exportImportResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            67 => 
            array (
                'id' => 68,
                'core_menu_items_id' => 46,
                'core_modules_id' => 28,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            68 => 
            array (
                'id' => 69,
                'core_menu_items_id' => 46,
                'core_modules_id' => 28,
                'name' => 'addSpecialPersonStatus',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            69 => 
            array (
                'id' => 70,
                'core_menu_items_id' => 46,
                'core_modules_id' => 28,
                'name' => 'updateSpecialPersonStatus',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            70 => 
            array (
                'id' => 71,
                'core_menu_items_id' => 46,
                'core_modules_id' => 28,
                'name' => 'deleteSpecialPersonStatus',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            71 => 
            array (
                'id' => 72,
                'core_menu_items_id' => 48,
                'core_modules_id' => 29,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            72 => 
            array (
                'id' => 73,
                'core_menu_items_id' => 48,
                'core_modules_id' => 29,
                'name' => 'createWorktimeLimit',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            73 => 
            array (
                'id' => 74,
                'core_menu_items_id' => 48,
                'core_modules_id' => 29,
                'name' => 'editWorktimeLimit',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            74 => 
            array (
                'id' => 75,
                'core_menu_items_id' => 48,
                'core_modules_id' => 29,
                'name' => 'deleteWorktimeLimit',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            75 => 
            array (
                'id' => 76,
                'core_menu_items_id' => 48,
                'core_modules_id' => 29,
                'name' => 'renewWorktimeLimit',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            76 => 
            array (
                'id' => 77,
                'core_menu_items_id' => 49,
                'core_modules_id' => 29,
                'name' => 'assignWorktimeLimit',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            77 => 
            array (
                'id' => 78,
                'core_menu_items_id' => 50,
                'core_modules_id' => 30,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            78 => 
            array (
                'id' => 79,
                'core_menu_items_id' => 50,
                'core_modules_id' => 30,
                'name' => 'setLeavers',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            79 => 
            array (
                'id' => 80,
                'core_menu_items_id' => 51,
                'core_modules_id' => 26,
                'name' => 'exportindex',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            80 => 
            array (
                'id' => 81,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 31,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            81 => 
            array (
                'id' => 82,
                'core_menu_items_id' => 34,
                'core_modules_id' => 20,
                'name' => 'generatePdfForSingleLegalEntity',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            82 => 
            array (
                'id' => 83,
                'core_menu_items_id' => 48,
                'core_modules_id' => 29,
                'name' => 'deleteWorktimeLimitCycle',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            83 => 
            array (
                'id' => 84,
                'core_menu_items_id' => 53,
                'core_modules_id' => 32,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            84 => 
            array (
                'id' => 85,
                'core_menu_items_id' => 53,
                'core_modules_id' => 32,
                'name' => 'showCreateForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            85 => 
            array (
                'id' => 86,
                'core_menu_items_id' => 53,
                'core_modules_id' => 32,
                'name' => 'showEditForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            86 => 
            array (
                'id' => 87,
                'core_menu_items_id' => 54,
                'core_modules_id' => 33,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            87 => 
            array (
                'id' => 88,
                'core_menu_items_id' => 55,
                'core_modules_id' => 34,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            88 => 
            array (
                'id' => 89,
                'core_menu_items_id' => 56,
                'core_modules_id' => 6,
                'name' => 'showCarriedBalances',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            89 => 
            array (
                'id' => 90,
                'core_menu_items_id' => 57,
                'core_modules_id' => 35,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            90 => 
            array (
                'id' => 91,
                'core_menu_items_id' => 58,
                'core_modules_id' => 13,
                'name' => 'legalEntityRenameForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            91 => 
            array (
                'id' => 92,
                'core_menu_items_id' => 59,
                'core_modules_id' => 36,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            92 => 
            array (
                'id' => 93,
                'core_menu_items_id' => 59,
                'core_modules_id' => 36,
                'name' => 'saveExportResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            93 => 
            array (
                'id' => 94,
                'core_menu_items_id' => 60,
                'core_modules_id' => 37,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            94 => 
            array (
                'id' => 96,
                'core_menu_items_id' => 61,
                'core_modules_id' => 20,
                'name' => 'attendancesheetsxlsexportindex',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            95 => 
            array (
                'id' => 97,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 35,
                'name' => 'exportBatchConfirmations',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            96 => 
            array (
                'id' => 98,
                'core_menu_items_id' => 62,
                'core_modules_id' => 38,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            97 => 
            array (
                'id' => 99,
                'core_menu_items_id' => 62,
                'core_modules_id' => 38,
                'name' => 'createReportForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            98 => 
            array (
                'id' => 100,
                'core_menu_items_id' => 62,
                'core_modules_id' => 38,
                'name' => 'createReport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            99 => 
            array (
                'id' => 101,
                'core_menu_items_id' => 62,
                'core_modules_id' => 38,
                'name' => 'updateReportForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            100 => 
            array (
                'id' => 102,
                'core_menu_items_id' => 62,
                'core_modules_id' => 38,
                'name' => 'updateReport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            101 => 
            array (
                'id' => 103,
                'core_menu_items_id' => 62,
                'core_modules_id' => 38,
                'name' => 'deleteReport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            102 => 
            array (
                'id' => 104,
                'core_menu_items_id' => 62,
                'core_modules_id' => 38,
                'name' => 'getReportResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            103 => 
            array (
                'id' => 105,
                'core_menu_items_id' => 63,
                'core_modules_id' => 39,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            104 => 
            array (
                'id' => 106,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 39,
                'name' => 'exportAbscences',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            105 => 
            array (
                'id' => 107,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 39,
                'name' => 'exportAbscencePlannerResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            106 => 
            array (
                'id' => 108,
                'core_menu_items_id' => 59,
                'core_modules_id' => 36,
                'name' => 'downloadExportFile',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            107 => 
            array (
                'id' => 109,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 20,
                'name' => 'generateSimpleXlsForLegalEntities',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            108 => 
            array (
                'id' => 110,
                'core_menu_items_id' => 64,
                'core_modules_id' => 40,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            109 => 
            array (
                'id' => 111,
                'core_menu_items_id' => 66,
                'core_modules_id' => 20,
                'name' => 'attendancesheetspdfexportindex',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            110 => 
            array (
                'id' => 112,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 20,
                'name' => 'generatePdfForLegalEntities',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            111 => 
            array (
                'id' => 113,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 20,
                'name' => 'generateDetailedXlsForLegalEntities',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            112 => 
            array (
                'id' => 114,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 13,
                'name' => 'exportReopenLegalEntities',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            113 => 
            array (
                'id' => 115,
                'core_menu_items_id' => 68,
                'core_modules_id' => 41,
                'name' => 'classification',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            114 => 
            array (
                'id' => 116,
                'core_menu_items_id' => 68,
                'core_modules_id' => 41,
                'name' => 'exportClassification',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            115 => 
            array (
                'id' => 117,
                'core_menu_items_id' => 69,
                'core_modules_id' => 41,
                'name' => 'changeClassification',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            116 => 
            array (
                'id' => 118,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 2,
                'name' => 'exportResetPasswordResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            117 => 
            array (
                'id' => 119,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 2,
                'name' => 'saveHierarchy',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            118 => 
            array (
                'id' => 120,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 2,
                'name' => 'viewProfilePictureEditor',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            119 => 
            array (
                'id' => 121,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 2,
                'name' => 'updateProfilePicture',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            120 => 
            array (
                'id' => 122,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 2,
                'name' => 'deleteProfilePicture',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            121 => 
            array (
                'id' => 123,
                'core_menu_items_id' => 54,
                'core_modules_id' => 33,
                'name' => 'saveOvertimeOrdinationResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            122 => 
            array (
                'id' => 124,
                'core_menu_items_id' => 8,
                'core_modules_id' => 2,
                'name' => 'filteredList',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            123 => 
            array (
                'id' => 125,
                'core_menu_items_id' => 70,
                'core_modules_id' => 33,
                'name' => 'deleteOvertimes',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            124 => 
            array (
                'id' => 126,
                'core_menu_items_id' => 70,
                'core_modules_id' => 33,
                'name' => 'saveOvertimeDeletionResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            125 => 
            array (
                'id' => 127,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 38,
                'name' => 'viewCustomReportEditor',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            126 => 
            array (
                'id' => 128,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 38,
                'name' => 'createCustomReport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            127 => 
            array (
                'id' => 129,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 38,
                'name' => 'updateCustomReport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            128 => 
            array (
                'id' => 130,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 38,
                'name' => 'deleteCustomReport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            129 => 
            array (
                'id' => 131,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 38,
                'name' => 'getCustomReportResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            130 => 
            array (
                'id' => 132,
                'core_menu_items_id' => 72,
                'core_modules_id' => 42,
                'name' => 'orderForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            131 => 
            array (
                'id' => 133,
                'core_menu_items_id' => 73,
                'core_modules_id' => 42,
                'name' => 'deleteForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            132 => 
            array (
                'id' => 134,
                'core_menu_items_id' => 72,
                'core_modules_id' => 42,
                'name' => 'saveFullDayBonusOrderResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            133 => 
            array (
                'id' => 135,
                'core_menu_items_id' => 73,
                'core_modules_id' => 42,
                'name' => 'saveFullDayBonusDeleteResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            134 => 
            array (
                'id' => 136,
                'core_menu_items_id' => 74,
                'core_modules_id' => 25,
                'name' => 'importAbscenceData',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            135 => 
            array (
                'id' => 137,
                'core_menu_items_id' => 74,
                'core_modules_id' => 25,
                'name' => 'saveimportAbscenceDataResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            136 => 
            array (
                'id' => 138,
                'core_menu_items_id' => 74,
                'core_modules_id' => 25,
                'name' => 'validateUploadedAbscenceFile',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            137 => 
            array (
                'id' => 139,
                'core_menu_items_id' => 74,
                'core_modules_id' => 25,
                'name' => 'processAbscenceImport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            138 => 
            array (
                'id' => 140,
                'core_menu_items_id' => 18,
                'core_modules_id' => 8,
                'name' => 'newShift',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            139 => 
            array (
                'id' => 141,
                'core_menu_items_id' => 18,
                'core_modules_id' => 8,
                'name' => 'createShift',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            140 => 
            array (
                'id' => 142,
                'core_menu_items_id' => 18,
                'core_modules_id' => 8,
                'name' => 'editShift',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            141 => 
            array (
                'id' => 143,
                'core_menu_items_id' => 18,
                'core_modules_id' => 8,
                'name' => 'updateShift',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            142 => 
            array (
                'id' => 144,
                'core_menu_items_id' => 75,
                'core_modules_id' => 43,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            143 => 
            array (
                'id' => 145,
                'core_menu_items_id' => 75,
                'core_modules_id' => 43,
                'name' => 'newStandbyType',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            144 => 
            array (
                'id' => 146,
                'core_menu_items_id' => 75,
                'core_modules_id' => 43,
                'name' => 'editStandbyType',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            145 => 
            array (
                'id' => 147,
                'core_menu_items_id' => 75,
                'core_modules_id' => 43,
                'name' => 'saveStandbyType',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            146 => 
            array (
                'id' => 148,
                'core_menu_items_id' => 75,
                'core_modules_id' => 43,
                'name' => 'updateStandbyType',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            147 => 
            array (
                'id' => 149,
                'core_menu_items_id' => 76,
                'core_modules_id' => 44,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            148 => 
            array (
                'id' => 150,
                'core_menu_items_id' => 76,
                'core_modules_id' => 44,
                'name' => 'editProfitCenter',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            149 => 
            array (
                'id' => 151,
                'core_menu_items_id' => 76,
                'core_modules_id' => 44,
                'name' => 'updateProfitCenter',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            150 => 
            array (
                'id' => 152,
                'core_menu_items_id' => 48,
                'core_modules_id' => 29,
                'name' => 'showWorktimeLimitCreateForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            151 => 
            array (
                'id' => 153,
                'core_menu_items_id' => 48,
                'core_modules_id' => 29,
                'name' => 'showWorktimeLimitEditForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            152 => 
            array (
                'id' => 154,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 45,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 1,
                'action_without_menu' => 0,
            ),
            153 => 
            array (
                'id' => 155,
                'core_menu_items_id' => 77,
                'core_modules_id' => 24,
                'name' => 'showDeleteBatch',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            154 => 
            array (
                'id' => 156,
                'core_menu_items_id' => 77,
                'core_modules_id' => 24,
                'name' => 'downloadBatchDeletionResults',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            155 => 
            array (
                'id' => 158,
                'core_menu_items_id' => 78,
                'core_modules_id' => 43,
                'name' => 'showBatchAssignment',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            156 => 
            array (
                'id' => 159,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 43,
                'name' => 'exportBatchAssignment',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            157 => 
            array (
                'id' => 160,
                'core_menu_items_id' => 79,
                'core_modules_id' => 36,
                'name' => 'exportSAPData',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            158 => 
            array (
                'id' => 161,
                'core_menu_items_id' => 79,
                'core_modules_id' => 36,
                'name' => 'downloadSAPExportFile',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            159 => 
            array (
                'id' => 162,
                'core_menu_items_id' => 80,
                'core_modules_id' => 36,
                'name' => 'showWorktimeJustification',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            160 => 
            array (
                'id' => 163,
                'core_menu_items_id' => 80,
                'core_modules_id' => 36,
                'name' => 'downloadWorktimeJustificationFile',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            161 => 
            array (
                'id' => 164,
                'core_menu_items_id' => 81,
                'core_modules_id' => 36,
                'name' => 'workdayDivisionExport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            162 => 
            array (
                'id' => 165,
                'core_menu_items_id' => 81,
                'core_modules_id' => 36,
                'name' => 'downloadWorkdayDivisionExportFile',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            163 => 
            array (
                'id' => 166,
                'core_menu_items_id' => 49,
                'core_modules_id' => 29,
                'name' => 'exportBatchAssignment',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            164 => 
            array (
                'id' => 167,
                'core_menu_items_id' => 92,
                'core_modules_id' => 29,
                'name' => 'editWorktimeLimitAssignment',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            165 => 
            array (
                'id' => 168,
                'core_menu_items_id' => 92,
                'core_modules_id' => 29,
                'name' => 'updateWorktimeLimitAssignment',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            166 => 
            array (
                'id' => 169,
                'core_menu_items_id' => 92,
                'core_modules_id' => 29,
                'name' => 'deleteWorktimeLimitAssignment',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            167 => 
            array (
                'id' => 170,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 36,
                'name' => 'showWorktimeStatement',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            168 => 
            array (
                'id' => 171,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 36,
                'name' => 'downloadWorktimeStatementFile',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            169 => 
            array (
                'id' => 172,
                'core_menu_items_id' => 34,
                'core_modules_id' => 20,
                'name' => 'specialPermissionForCalendarApproval',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            170 => 
            array (
                'id' => 173,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 46,
                'name' => 'importDataFromAccountingSoftware',
                'is_api' => 1,
                'description' => 'Baber xml import adatainak beemelése az e-jelenlétbe',
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            171 => 
            array (
                'id' => 174,
                'core_menu_items_id' => 60,
                'core_modules_id' => 37,
                'name' => 'exportScheduledMonthToXlsx',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            172 => 
            array (
                'id' => 175,
                'core_menu_items_id' => 57,
                'core_modules_id' => 35,
                'name' => 'exportBatchConfirmationsToXlsx',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            173 => 
            array (
                'id' => 176,
                'core_menu_items_id' => 85,
                'core_modules_id' => 29,
                'name' => 'worktimeLimitBatchDeletion',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            174 => 
            array (
                'id' => 177,
                'core_menu_items_id' => 85,
                'core_modules_id' => 29,
                'name' => 'deleteWorktimelimitPdfExport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            175 => 
            array (
                'id' => 178,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 46,
                'name' => 'exportApiImportLog',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            176 => 
            array (
                'id' => 179,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 47,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 1,
                'action_without_menu' => 0,
            ),
            177 => 
            array (
                'id' => 180,
                'core_menu_items_id' => 86,
                'core_modules_id' => 2,
                'name' => 'forcedPasswordRefreshment',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            178 => 
            array (
                'id' => 181,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 46,
                'name' => 'downloadDetails',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            179 => 
            array (
                'id' => 182,
                'core_menu_items_id' => 87,
                'core_modules_id' => 48,
                'name' => 'sorting',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            180 => 
            array (
                'id' => 183,
                'core_menu_items_id' => 88,
                'core_modules_id' => 48,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            181 => 
            array (
                'id' => 184,
                'core_menu_items_id' => 88,
                'core_modules_id' => 48,
                'name' => 'showEditForm',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            182 => 
            array (
                'id' => 185,
                'core_menu_items_id' => 90,
                'core_modules_id' => 48,
                'name' => 'exportSetting',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            183 => 
            array (
                'id' => 186,
                'core_menu_items_id' => 89,
                'core_modules_id' => 3,
                'name' => 'downloadLogFilesToXlsx',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            184 => 
            array (
                'id' => 187,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 48,
                'name' => 'addNewExportSetting',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            185 => 
            array (
                'id' => 188,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 48,
                'name' => 'createNewExportSetting',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            186 => 
            array (
                'id' => 189,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 48,
                'name' => 'modifyExportSetting',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            187 => 
            array (
                'id' => 190,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 48,
                'name' => 'modifySavedExportSetting',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            188 => 
            array (
                'id' => 191,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 48,
                'name' => 'removeExportSetting',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            189 => 
            array (
                'id' => 192,
                'core_menu_items_id' => 91,
                'core_modules_id' => 14,
                'name' => 'cleanerIndex',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            190 => 
            array (
                'id' => 193,
                'core_menu_items_id' => 91,
                'core_modules_id' => 14,
                'name' => 'checkHierarchyDifferences',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            191 => 
            array (
                'id' => 194,
                'core_menu_items_id' => 91,
                'core_modules_id' => 14,
                'name' => 'downloadHierarchyCleaningLogs',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            192 => 
            array (
                'id' => 195,
                'core_menu_items_id' => 89,
                'core_modules_id' => 3,
                'name' => 'downloadLogFiles',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            193 => 
            array (
                'id' => 199,
                'core_menu_items_id' => 2,
                'core_modules_id' => 2,
                'name' => 'showLegalEntities',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            194 => 
            array (
                'id' => 200,
                'core_menu_items_id' => 35,
                'core_modules_id' => 21,
                'name' => 'downloadWorkplansToXlsx',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            195 => 
            array (
                'id' => 201,
                'core_menu_items_id' => 93,
                'core_modules_id' => 49,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            196 => 
            array (
                'id' => 202,
                'core_menu_items_id' => 93,
                'core_modules_id' => 49,
                'name' => 'getdocument',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            197 => 
            array (
                'id' => 203,
                'core_menu_items_id' => 60,
                'core_modules_id' => 37,
                'name' => 'exportScheduledIntervalToXlsx',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            198 => 
            array (
                'id' => 204,
                'core_menu_items_id' => 94,
                'core_modules_id' => 50,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            199 => 
            array (
                'id' => 205,
                'core_menu_items_id' => 94,
                'core_modules_id' => 50,
                'name' => 'validateFiles',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            200 => 
            array (
                'id' => 206,
                'core_menu_items_id' => 94,
                'core_modules_id' => 50,
                'name' => 'importFiles',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            201 => 
            array (
                'id' => 207,
                'core_menu_items_id' => 95,
                'core_modules_id' => 18,
                'name' => 'wrongEmailNotificationsIndex',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            202 => 
            array (
                'id' => 208,
                'core_menu_items_id' => 96,
                'core_modules_id' => 51,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            203 => 
            array (
                'id' => 209,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 51,
                'name' => 'export',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            204 => 
            array (
                'id' => 210,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 51,
                'name' => 'exportToIkea',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            205 => 
            array (
                'id' => 211,
                'core_menu_items_id' => 97,
                'core_modules_id' => 20,
                'name' => 'attendanceSheetAllDetailsExport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            206 => 
            array (
                'id' => 212,
                'core_menu_items_id' => 97,
                'core_modules_id' => 20,
                'name' => 'generateExtendsPdfForLegalEntities',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            207 => 
            array (
                'id' => 213,
                'core_menu_items_id' => 97,
                'core_modules_id' => 20,
                'name' => 'generateAllXlsForLegalEntities',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            208 => 
            array (
                'id' => 214,
                'core_menu_items_id' => 98,
                'core_modules_id' => 52,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            209 => 
            array (
                'id' => 215,
                'core_menu_items_id' => 101,
                'core_modules_id' => 53,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            210 => 
            array (
                'id' => 216,
                'core_menu_items_id' => 101,
                'core_modules_id' => 53,
                'name' => 'create',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            211 => 
            array (
                'id' => 217,
                'core_menu_items_id' => 101,
                'core_modules_id' => 53,
                'name' => 'copy',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            212 => 
            array (
                'id' => 218,
                'core_menu_items_id' => 101,
                'core_modules_id' => 53,
                'name' => 'edit',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            213 => 
            array (
                'id' => 219,
                'core_menu_items_id' => 101,
                'core_modules_id' => 53,
                'name' => 'updateHolidayRule',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            214 => 
            array (
                'id' => 220,
                'core_menu_items_id' => 101,
                'core_modules_id' => 53,
                'name' => 'delete',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            215 => 
            array (
                'id' => 221,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 39,
                'name' => 'exportAbscencePlannerResultsToXLSX',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            216 => 
            array (
                'id' => 222,
                'core_menu_items_id' => NULL,
                'core_modules_id' => 3,
                'name' => 'downloadAccessControllImport',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 0,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            217 => 
            array (
                'id' => 223,
                'core_menu_items_id' => 102,
                'core_modules_id' => 53,
                'name' => 'addLegalEntities',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            218 => 
            array (
                'id' => 225,
                'core_menu_items_id' => 100,
                'core_modules_id' => 56,
                'name' => 'index',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            219 => 
            array (
                'id' => 501,
                'core_menu_items_id' => 34,
                'core_modules_id' => 20,
                'name' => 'day_details',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 1,
            ),
            220 => 
            array (
                'id' => 502,
                'core_menu_items_id' => 34,
                'core_modules_id' => 20,
                'name' => 'abscence',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 1,
            ),
            221 => 
            array (
                'id' => 503,
                'core_menu_items_id' => 34,
                'core_modules_id' => 20,
                'name' => 'add_shift',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 1,
            ),
            222 => 
            array (
                'id' => 504,
                'core_menu_items_id' => 34,
                'core_modules_id' => 20,
                'name' => 'add_places_of_work',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 1,
            ),
            223 => 
            array (
                'id' => 505,
                'core_menu_items_id' => 34,
                'core_modules_id' => 20,
                'name' => 'confirmation',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 1,
            ),
            224 => 
            array (
                'id' => 506,
                'core_menu_items_id' => 34,
                'core_modules_id' => 20,
                'name' => 'rejection',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 1,
            ),
            225 => 
            array (
                'id' => 507,
                'core_menu_items_id' => 63,
                'core_modules_id' => 39,
                'name' => 'editing',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 1,
            ),
            226 => 
            array (
                'id' => 508,
                'core_menu_items_id' => 104,
                'core_modules_id' => 58,
                'name' => 'pekseg_uzletek',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
            227 => 
            array (
                'id' => 509,
                'core_menu_items_id' => 105,
                'core_modules_id' => 57,
                'name' => 'pekseg_dolgozok',
                'is_api' => 0,
                'description' => NULL,
                'is_visible' => 1,
                'default_permission_level' => 0,
                'action_without_menu' => 0,
            ),
        ));

        
    }
}