<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'Test User',
            'email' => 'test@example.com',
        ]);
        $this->call(AttendanceAbscenceTypesTableSeeder::class);
        $this->call(AttendanceAbscenceTypesCoreFirmsRelTableSeeder::class);
        $this->call(AttendanceAccessControlSystemsTableSeeder::class);
        $this->call(AttendanceAccessControlSystemsCalendarRelTableSeeder::class);
        $this->call(AttendanceAccessControlSystemsExtraAddressesTableSeeder::class);
        $this->call(AttendanceAccessControlSystemsRulesTableSeeder::class);
        $this->call(AttendanceApprovalButtonsTableSeeder::class);
        $this->call(AttendanceApprovalLinksTableSeeder::class);
        $this->call(AttendanceAttendanceEntitySelectorSettingsTableSeeder::class);
        $this->call(AttendanceAttendanceSheetExportSettingsTableSeeder::class);
        $this->call(AttendanceAttendanceSheetSettingsTableSeeder::class);
        $this->call(AttendanceBonusTypesTableSeeder::class);
        $this->call(AttendanceDayTypesTableSeeder::class);
        $this->call(AttendanceHolidayRuleSchedulesTableSeeder::class);
        $this->call(AttendanceHolidayRuleSchedulesPermissionGroupsRelTableSeeder::class);
        $this->call(AttendanceHolidayRulesTableSeeder::class);
        $this->call(AttendanceHolidayRulesLegalEntitiesRelTableSeeder::class);
        $this->call(AttendanceLegalEntitiesAbscencesTableSeeder::class);
        $this->call(AttendanceLegalEntitiesBonusesWithinShiftTableSeeder::class);
        $this->call(AttendanceLegalEntitiesCalendarTableSeeder::class);
        $this->call(AttendanceLegalEntitiesCalendarAttendancePlacesOfWorkRelTableSeeder::class);
        $this->call(AttendanceLegalEntitiesCalendarRejectionsTableSeeder::class);
        $this->call(AttendanceLegalEntitiesCarriedBalanceTableSeeder::class);
        $this->call(AttendanceLegalEntitiesDetailsBackupTableSeeder::class);
        $this->call(AttendanceLegalEntitiesHolidayAmountsTableSeeder::class);
        $this->call(AttendanceLegalEntitiesOutsideShiftsTimeTableSeeder::class);
        $this->call(AttendanceLegalEntitiesOutsideShiftsTimeBonusesRelTableSeeder::class);
        $this->call(AttendanceLegalEntitiesOvertimesTableSeeder::class);
        $this->call(AttendanceLegalEntitiesOvertimesBonusesRelTableSeeder::class);
        $this->call(AttendanceLegalEntitiesShiftsTableSeeder::class);
        $this->call(AttendanceLegalEntitiesShiftsBalancesTableSeeder::class);
        $this->call(AttendanceLegalEntitiesShiftsWorkhoursTableSeeder::class);
        $this->call(AttendanceLegalStockTableSeeder::class);
        $this->call(AttendanceOffdayTypesTableSeeder::class);
        $this->call(AttendanceOffdayTypesCoreFirmsOrderTableSeeder::class);
        $this->call(AttendancePlacesOfWorkTableSeeder::class);
        $this->call(AttendancePlacesOfWorkBonusesRelTableSeeder::class);
        $this->call(AttendanceRoundingSettingsTableSeeder::class);
        $this->call(AttendanceSchedulerTemplatesTableSeeder::class);
        $this->call(AttendanceShiftBreaksTableSeeder::class);
        $this->call(AttendanceShiftTypesTableSeeder::class);
        $this->call(AttendanceStandbyOvertimesTableSeeder::class);
        $this->call(AttendanceStandbyTypesTableSeeder::class);
        $this->call(AttendanceVerificationConditionSystemsTableSeeder::class);
        $this->call(AttendanceVerificationConditionValuesTableSeeder::class);
        $this->call(AttendanceVerificationConditionsTableSeeder::class);
        $this->call(AttendanceVerificationConditionsDetailsTableSeeder::class);
        $this->call(AttendanceVerificationConditionsParametersTableSeeder::class);
        $this->call(AttendanceWorkdayDivisionExportSettingsTableSeeder::class);
        $this->call(AttendanceWorkdayDivisionsTableSeeder::class);
        $this->call(AttendanceWorkdayDivisionsOrderTableSeeder::class);
        $this->call(AttendanceWorkplanCategoriesTableSeeder::class);
        $this->call(AttendanceWorkplanShiftsTableSeeder::class);
        $this->call(AttendanceWorkplansTableSeeder::class);
        $this->call(AttendanceWorkplansAdditionalBonusesTableSeeder::class);
        $this->call(AttendanceWorkplansCoreLegalEntitiesRelTableSeeder::class);
        $this->call(AttendanceWorkplansFullDayBonusesTableSeeder::class);
        $this->call(AttendanceWorktimelimitAbscenceBonusTableSeeder::class);
        $this->call(AttendanceWorktimelimitAbscencesTableSeeder::class);
        $this->call(AttendanceWorktimelimitAssignmentsTableSeeder::class);
        $this->call(AttendanceWorktimelimitDeficitTableSeeder::class);
        $this->call(AttendanceWorktimelimitExcessTableSeeder::class);
        $this->call(AttendanceWorktimelimitRestTimeDifferenceBonusTableSeeder::class);
        $this->call(AttendanceWorktimelimitsTableSeeder::class);
        $this->call(CoreActionsTableSeeder::class);
        $this->call(CoreActivitiesTableSeeder::class);
        $this->call(CoreAllowCronJobTableSeeder::class);
        $this->call(CoreBasicCalendarTableSeeder::class);
        $this->call(CoreCitiesTableSeeder::class);
        $this->call(CoreComponentsTableSeeder::class);
        $this->call(CoreCostCentersTableSeeder::class);
        $this->call(CoreCountiesTableSeeder::class);
        $this->call(CoreCustomReportsTableSeeder::class);
        $this->call(CoreDepartmentsTableSeeder::class);
        $this->call(CoreEmailIdentificationTableSeeder::class);
        $this->call(CoreEmailNotificationSubjectsTableSeeder::class);
        $this->call(CoreEmailNotificationTypesTableSeeder::class);
        $this->call(CoreEmailNotificationsTableSeeder::class);
        $this->call(CoreEstablishmentsTableSeeder::class);
        $this->call(CoreExtendedHierarchyTableSeeder::class);
        $this->call(CoreExtraEmailAddressesTableSeeder::class);
        $this->call(CoreExtraPermissionCoreModulesCoreFirmsRelTableSeeder::class);
        $this->call(CoreFirmsTableSeeder::class);
        $this->call(CoreFirmsCoreComponentsRelTableSeeder::class);
        $this->call(CoreGeneralLedgerAnalyticsTableSeeder::class);
        $this->call(CoreGeneralLedgerAnalyticsValueTableSeeder::class);
        $this->call(CoreHierarchyTableSeeder::class);
        $this->call(CoreHierarchyImportTableSeeder::class);
        $this->call(CoreHierarchyUpdaterTableSeeder::class);
        $this->call(CoreHierarchyUpdaterLogsTableSeeder::class);
        $this->call(CoreHolidaysTableSeeder::class);
        $this->call(CoreLegalEntitiesTableSeeder::class);
        $this->call(CoreLegalEntitiesAttributesTableSeeder::class);
        $this->call(CoreLegalEntitiesAttributesLabelsTableSeeder::class);
        $this->call(CoreLegalEntitiesAttributesValuesTableSeeder::class);
        $this->call(CoreLegalEntitiesCoreActivitiesAssignmentsTableSeeder::class);
        $this->call(CoreLegalEntitiesCostCenterAssignmentsTableSeeder::class);
        $this->call(CoreLegalEntitiesDepartmentAssignmentsTableSeeder::class);
        $this->call(CoreLegalEntitiesEstablishmentAssignmentsTableSeeder::class);
        $this->call(CoreLegalEntitiesGeneralLedgerAnalyticValueAssignmentsTableSeeder::class);
        $this->call(CoreLegalEntitiesProfitCenterAssignmentsTableSeeder::class);
        $this->call(CoreLegalEntitiesSystemAttributesTableSeeder::class);
        $this->call(CoreLocalizationTableSeeder::class);
        $this->call(CoreLogMessagesTableSeeder::class);
        $this->call(CoreLogsTableSeeder::class);
        $this->call(CoreMenuItemsTableSeeder::class);
        $this->call(CoreModulesTableSeeder::class);
        $this->call(CoreOtherIncomesTableSeeder::class);
        $this->call(CoreParameterValuesTableSeeder::class);
        $this->call(CoreParametersTableSeeder::class);
        $this->call(CoreParametersCoreFirmsStatusTableSeeder::class);
        $this->call(CoreParametersCoreFirmsValuesTableSeeder::class);
        $this->call(CoreParametersCoreParameterValuesRelTableSeeder::class);
        $this->call(CorePasswordsLogsTableSeeder::class);
        $this->call(CorePermissionGroupsTableSeeder::class);
        $this->call(CorePermissionGroupsActionPermissionsRelTableSeeder::class);
        $this->call(CorePermissionGroupsCoreLegalEntitiesRelTableSeeder::class);
        $this->call(CorePersonDetectionEnvironmentsTableSeeder::class);
        $this->call(CorePersonsTableSeeder::class);
        $this->call(CorePersonsAttributesTableSeeder::class);
        $this->call(CorePersonsAttributesLabelsTableSeeder::class);
        $this->call(CorePersonsAttributesValuesTableSeeder::class);
        $this->call(CorePersonsSystemAttributesTableSeeder::class);
        $this->call(CoreProfitCentersTableSeeder::class);
        $this->call(CorePublicPlacesTableSeeder::class);
        $this->call(CoreReportCategoriesTableSeeder::class);
        $this->call(CoreReportClassesTableSeeder::class);
        $this->call(CoreReportsTableSeeder::class);
        $this->call(CoreSavedLegalEntityFiltersTableSeeder::class);
        $this->call(CoreSessionContainerTableSeeder::class);
        $this->call(CoreSpecialPermissionsTableSeeder::class);
        $this->call(CoreSpecialPermissionsCoreActionsRelTableSeeder::class);
        $this->call(CoreSpecialPersonStatusTypesTableSeeder::class);
        $this->call(CoreSpecialPersonStatusesTableSeeder::class);
        $this->call(CoreSsoOauthClientsTableSeeder::class);
        $this->call(CoreSubdomainAttributesTableSeeder::class);
        $this->call(CoreSubstitutionsTableSeeder::class);
        $this->call(CoreSurfaceNotificationsTableSeeder::class);
        $this->call(CoreTemporaryHierarchyTableSeeder::class);
        $this->call(CoreUniqueReportsTableSeeder::class);
        $this->call(CoreUniqueReportsStructureTableSeeder::class);
        $this->call(SyncApiTokenTableSeeder::class);
        $this->call(SyncTokenActionsRelTableSeeder::class);
    }
}
